--- #YAML:1.0
name:                Data-Pareto
version:             0.01
abstract:            Computing Pareto sets in Perl
license:             ~
author:              
    - Przemyslaw Wesolek <jest@go.art.pl>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
